const { format } = require("date-fns");

exports.docToCSV = (doc) => {
  return [
    doc.regional_origem,
    doc.regional,
    doc.loja_origem,
    doc.climate_cluster,
    doc.perfil_loja,
    doc.negocio,
    doc.divisao,
    doc.grupo_num,
    doc.grupo,
    doc.classe,
    doc.subclass_num,
    doc.subclasse,
    doc.sazonalidade_subclasse,
    doc.item_pai_nome,
    doc.item_pai,
    doc.cor_num,
    doc.cor_tam,
    doc.paicor,
    doc.itens,
    doc.gross_margin_value_financial.toString().replace(".", ","),
    doc.financial_sales.toString().replace(".", ","),
    doc.margem_de_lucro.toString().replace(".", ","),
    doc.vda_2w_lj_modelo,
    doc.eoh_loja_nec,
    doc.eoh_loja_modelo,
    doc.st_modelo.toString().replace(".", ","),
    doc.dif_equil.toString().replace(".", ","),
    doc.vda_2w_mod_ecom,
    doc.eoh_rj,
    doc.in_transit_rj,
    doc.alloc_rj,
    doc.qtd_interestadual,
    doc.st_ecommerce.toString().replace(".", ","),
    doc.dif_equil_ecom.toString().replace(".", ","),
    doc.eoh_it_cd,
    doc.sugestao,
    doc.status_vitrine,
    doc.piramide_mercadologica,
    doc.sazonalidade,
    doc.itens_fundamentais,
    doc.digital,
    doc.faixa_de_preco,
    doc.produtos,
    doc.flag_price_type,
    doc.idade_w_agrupado_bucket,
    doc.idade_w_bucket,
    doc.maximo_transferencia,
    doc.eoh_apresentacao,
    doc.max_retirada_apresentacao,
    doc.max_retirada,
    doc.grade,
    doc.priorizar,
    format(doc.data_inicio_app, "dd/MM/yyyy"),
    format(doc.data_final_app_prazo, "dd/MM/yyyy"),
    doc.semana_comercial,
    doc.numero_ot,
    doc.tipo_ot,
    doc.forma_ot,
    doc.loja_destino,
    doc.regional_destino,
    doc.score_priorizacao.toString().replace(".", ","),
    doc.score_smart.toString().replace(".", ","),
  ];
};

exports.createHeadersByColumns = () => {
  return [
    "regional_origem",
    "regional",
    "loja_origem",
    "climate_cluster",
    "perfil_loja",
    "negocio",
    "divisao",
    "grupo_num",
    "grupo",
    "classe",
    "subclass_num",
    "subclasse",
    "sazonalidade_subclasse",
    "item_pai_nome",
    "item_pai",
    "cor_num",
    "cor_tam",
    "paicor",
    "itens",
    "gross_margin_value_financial",
    "financial_sales",
    "margem_de_lucro",
    "vda_2w_lj_modelo",
    "eoh_loja_nec",
    "eoh_loja_modelo",
    "st_modelo",
    "dif_equil",
    "vda_2w_mod_ecom",
    "eoh_rj",
    "in_transit_rj",
    "alloc_rj",
    "qtd_interestadual",
    "st_ecommerce",
    "dif_equil_ecom",
    "eoh_it_cd",
    "sugestao",
    "status_vitrine",
    "piramide_mercadologica",
    "sazonalidade",
    "itens_fundamentais",
    "digital",
    "faixa_de_preco",
    "produtos",
    "flag_price_type",
    "idade_w_agrupado_bucket",
    "idade_w_bucket",
    "maximo_transferencia",
    "eoh_apresentacao",
    "max_retirada_apresentacao",
    "max_retirada",
    "grade",
    "priorizar",
    "data_inicio_app",
    "data_final_app_prazo",
    "semana_comercial",
    "numero_ot",
    "tipo_ot",
    "forma_ot",
    "loja_destino",
    "regional_destino",
    "score_priorizacao",
    "score_smart",
  ].map((item) => ({ header: item, key: item }));
};
